### ISSUE TITLE
Cannot resolve dependency

### ISSUE THREAD

**Issue by BenDol** [SolidAlloy/UnityDropdown#1]
An error occurred while resolving packages:
  Package com.solidalloy.unity-dropdown@https://github.com/SolidAlloy/UnityDropdown.git has invalid dependencies or related test packages:
    org.nuget.system.memory (dependency): Package [org.nuget.system.memory@4.5.4] cannot be found

A re-import of the project may be required to fix the issue or a manual modification of C:/Projects/Unity/xxx/Packages/manifest.json file.

**Comment by SolidAlloy** [comment]
Hi, thanks for reporting the issue. I updated the installation instructions so that they don't cause issues like this anymore. The new installation steps are below:

1. In Unity, open **Project Settings** -> **Package Manager**.
2. Add a new scoped registry with the following details:
   - **Name**: package.openupm.com
   - **URL**: https://package.openupm.com
   - Scope(s):
     - com.openupm
     - com.solidalloy
     - org.nuget
3. Hit **Apply**.
4. Go to **Window** -> **Package Manager**.
5. Press the **+** button, *Add package from git URL*.
6. Enter **com.solidalloy.unity-dropdown**, press **Add**.
